### ISSUE TITLE
Remove dependency from LGPL library

### ISSUE THREAD

**Issue by starix** [gherynos/libsaltpack#2]
LGPL library are used in 2 functions: **baseXencode** and **baseXdecode**.
Please rewrite this 2 functions to drop dependency of GMP (MPIR).

Reason: LGPL do not allow a static link of library in closed-source projects.

**Comment by gherynos** [comment]
Good point, thanks for raising: I'm working on a different solution for the BigInt dependency.

**Comment by gherynos** [comment]
Just released a new version [0.3.0](https://github.com/gherynos/libsaltpack/releases/tag/v0.3.0) which doesn't depend on GMP/MPIR.

The big integer library used is now [Num](https://github.com/983/Num), which is in public domain.
